server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://192.168.1.30:5432/postgres
    username: postgres
    password: pine1234!@#$
    driver-class-name: org.postgresql.Driver
  thymeleaf:
    prefix: classpath:templates/
    check-template-location: true
    suffix: .html
    mode: HTML
    cache: false



mybatis:
  type-aliases-package: com.example.demo.vo
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:mapper/**/*.xml
